feat: Handle Directory Imports, Node Builtins
favware/esbuild-plugin-file-path-extensions pull request #104
Opened 2024-05-06 22:51 UTC by BeeeQueue

- **test: add node builtins tests**
- **feat: implement node builtin exception**
- **feat: implement directory import check**

2024-05-09 14:41 UTC, favna requested changes
I'm not yet sure why but this seems to fail on Windows (11, x64) where my snapshots update to invalid imports:

![image](https://github.com/favware/esbuild-plugin-file-path-extensions/assets/4019718/bdf3ba33-ca41-437e-b0a7-0a3529ccf207)

(Granted the old snapshots weren't correct either but the diff here should be the removal of `.cjs`)

2024-05-09 14:41 UTC, favna commented on src/index.ts
> +  if (builtins == null) {
```suggestion
  if (builtins === null) {
```

2024-05-09 21:07 UTC, BeeeQueue commented
I found that most snapshots have that error, so I updated those as well.

I couldn't see why it wasn't using esbuild's `format` option as the default so I added that to fix said snapshots.

I still have no idea why the last snapshot is failing, even after going stepby-step in the debugger...

2024-05-11 11:43 UTC, favna requested changes

2024-05-11 11:43 UTC, favna commented on tests/scenarios/node-builtins.test.ts
> +    format: 'esm',
```suggestion
    format: 'esm',
    outExtension: {
      '.js': '.mjs'
    },
```

This will fix the last 2 tests. Currently it outputs as `.js` which conflicts with line 18 and 26.

2024-05-11 23:53 UTC, favna approved these changes

2024-05-12 14:01 UTC, merged

2024-05-12 14:04 UTC, favna commented
I'll be honest I didn't realise you work for Paypal until I merged the PR and I saw your email in the commit body. That's pretty damn cool that my project is used at Paypal. That's pretty big for a simple open-source contributor like me. Thanks!!

2024-05-12 14:14 UTC, favna commented
Released in v2.1.0, not sure why GitHub doesn't detect it automatically.